### ISSUE TITLE
When a user who already has an account fills out the signup form, it shows the 'success' page

### ISSUE THREAD

**Issue by hashbrowncipher** [hacsoc/kraller#8]
The flows for once the user has an account are really raw. v2?

**Comment by imbstack** [comment]
This is on purpose.  They have an account already.  It flashes that there is already an account.

Close this unless this means that I should add a key update page.

**Comment by hashbrowncipher** [comment]
Yes, it flashes that they already have an account, but it shows the 'success' page.  I believe it says 'Yipee!' and then an error message.

**Comment by imbstack** [comment]
What if I change the error message to "This is a good thing?"
